require("dotenv").config();
import { ChromaInstance } from "./services/chroma";
import { chat } from "./services/openai";
import _ from "lodash";
import { LLMChain } from "langchain/chains";
import {
  ChatPromptTemplate,
  HumanMessagePromptTemplate,
  SystemMessagePromptTemplate,
} from "langchain/prompts";

import { MAX_TOKEN_QUESTION } from "./helpers/constants";
import { numTokens } from "./helpers/text";
import { getContext } from "./helpers/openai";

main();
async function main() {
  try {
    //const question = "based on the list papers '\"Why Are They Collecting My Data?\"- Inferring the Purposes of Network Traffic in Mobile Apps', 'A Study of User Privacy in Android Mobile AR Apps', 'Consistency Analysis of Data-Usage Purposes in Mobile Apps', 'Privacy and Security Analysis of mHealth Apps', 'Static Analysis for Android GDPR Complianc', 'An android intelligent mobile terminal application - field data survey system for forest fires', 'Needs, experiences, and views of people with rheumatic and musculoskeletal diseases on self-management mobile health apps - mixed methods study', 'Methods and Measures Used to Evaluate Patient-Operated Mobile Health Interventions - Scoping Literature Review', 'Hark - A Deep Learning System for Navigating Privacy Feedback at Scale', 'Features and characteristics of publicly available mHealth apps for self-management in chronic obstructive pulmonary disease', 'Detecting Malware by Analyzing App Permissions on Android Platform - A Systematic Literature Review' , summarize each paper very details?";
    //const question = "based on the list papers '\"Why Are They Collecting My Data?\"- Inferring the Purposes of Network Traffic in Mobile Apps', 'A Study of User Privacy in Android Mobile AR Apps', 'Consistency Analysis of Data-Usage Purposes in Mobile Apps', 'Privacy and Security Analysis of mHealth Apps', 'Static Analysis for Android GDPR Complianc', 'An android intelligent mobile terminal application - field data survey system for forest fires', 'Needs, experiences, and views of people with rheumatic and musculoskeletal diseases on self-management mobile health apps - mixed methods study', 'Methods and Measures Used to Evaluate Patient-Operated Mobile Health Interventions - Scoping Literature Review', 'Hark - A Deep Learning System for Navigating Privacy Feedback at Scale', 'Features and characteristics of publicly available mHealth apps for self-management in chronic obstructive pulmonary disease', 'Detecting Malware by Analyzing App Permissions on Android Platform - A Systematic Literature Review', Show me some gaps in the privacy compliance research that my study can fill?";
    //const question = "based on the list papers '\"Why Are They Collecting My Data?\"- Inferring the Purposes of Network Traffic in Mobile Apps', 'A Study of User Privacy in Android Mobile AR Apps', 'Consistency Analysis of Data-Usage Purposes in Mobile Apps', 'Privacy and Security Analysis of mHealth Apps', 'Static Analysis for Android GDPR Complianc', 'An android intelligent mobile terminal application - field data survey system for forest fires', 'Needs, experiences, and views of people with rheumatic and musculoskeletal diseases on self-management mobile health apps - mixed methods study', 'Methods and Measures Used to Evaluate Patient-Operated Mobile Health Interventions - Scoping Literature Review', 'Hark - A Deep Learning System for Navigating Privacy Feedback at Scale', 'Features and characteristics of publicly available mHealth apps for self-management in chronic obstructive pulmonary disease', 'Detecting Malware by Analyzing App Permissions on Android Platform - A Systematic Literature Review', What should my research questions or hypotheses in the 'Privacy compliance' topic?";
    //const question = "based on the list papers '\"Why Are They Collecting My Data?\"- Inferring the Purposes of Network Traffic in Mobile Apps', 'A Study of User Privacy in Android Mobile AR Apps', 'Consistency Analysis of Data-Usage Purposes in Mobile Apps', 'Privacy and Security Analysis of mHealth Apps', 'Static Analysis for Android GDPR Complianc', 'An android intelligent mobile terminal application - field data survey system for forest fires', 'Needs, experiences, and views of people with rheumatic and musculoskeletal diseases on self-management mobile health apps - mixed methods study', 'Methods and Measures Used to Evaluate Patient-Operated Mobile Health Interventions - Scoping Literature Review', 'Hark - A Deep Learning System for Navigating Privacy Feedback at Scale', 'Features and characteristics of publicly available mHealth apps for self-management in chronic obstructive pulmonary disease', 'Detecting Malware by Analyzing App Permissions on Android Platform - A Systematic Literature Review', how can I collect my data which, focus on 'Privacy compliance', in a way that is systematic, unbiased, and accurate?";
    //const question = "based on the list papers '\"Why Are They Collecting My Data?\"- Inferring the Purposes of Network Traffic in Mobile Apps', 'A Study of User Privacy in Android Mobile AR Apps', 'Consistency Analysis of Data-Usage Purposes in Mobile Apps', 'Privacy and Security Analysis of mHealth Apps', 'Static Analysis for Android GDPR Complianc', 'An android intelligent mobile terminal application - field data survey system for forest fires', 'Needs, experiences, and views of people with rheumatic and musculoskeletal diseases on self-management mobile health apps - mixed methods study', 'Methods and Measures Used to Evaluate Patient-Operated Mobile Health Interventions - Scoping Literature Review', 'Hark - A Deep Learning System for Navigating Privacy Feedback at Scale', 'Features and characteristics of publicly available mHealth apps for self-management in chronic obstructive pulmonary disease', 'Detecting Malware by Analyzing App Permissions on Android Platform - A Systematic Literature Review', what data analysis techniques are most suitable for the Privacy compliance outcomes, explain and show the corresponding papers?";
    //const question = "based on the list papers '\"Why Are They Collecting My Data?\"- Inferring the Purposes of Network Traffic in Mobile Apps', 'A Study of User Privacy in Android Mobile AR Apps', 'Consistency Analysis of Data-Usage Purposes in Mobile Apps', 'Privacy and Security Analysis of mHealth Apps', 'Static Analysis for Android GDPR Complianc', 'An android intelligent mobile terminal application - field data survey system for forest fires', 'Needs, experiences, and views of people with rheumatic and musculoskeletal diseases on self-management mobile health apps - mixed methods study', 'Methods and Measures Used to Evaluate Patient-Operated Mobile Health Interventions - Scoping Literature Review', 'Hark - A Deep Learning System for Navigating Privacy Feedback at Scale', 'Features and characteristics of publicly available mHealth apps for self-management in chronic obstructive pulmonary disease', 'Detecting Malware by Analyzing App Permissions on Android Platform - A Systematic Literature Review', Based on the list papers, how can I find the suitable journal to submit my research paper which focus on the ‘privacy compliance’?";
    //const question = "based on the list papers '\"Why Are They Collecting My Data?\"- Inferring the Purposes of Network Traffic in Mobile Apps', 'A Study of User Privacy in Android Mobile AR Apps', 'Consistency Analysis of Data-Usage Purposes in Mobile Apps', 'Privacy and Security Analysis of mHealth Apps', 'Static Analysis for Android GDPR Complianc', 'An android intelligent mobile terminal application - field data survey system for forest fires', 'Needs, experiences, and views of people with rheumatic and musculoskeletal diseases on self-management mobile health apps - mixed methods study', 'Methods and Measures Used to Evaluate Patient-Operated Mobile Health Interventions - Scoping Literature Review', 'Hark - A Deep Learning System for Navigating Privacy Feedback at Scale', 'Features and characteristics of publicly available mHealth apps for self-management in chronic obstructive pulmonary disease', 'Detecting Malware by Analyzing App Permissions on Android Platform - A Systematic Literature Review', Based on the list papers, can you list 5 the Journal/Conference and the corresponding papers which is suitable for our 'privacy compliance' article?";
    //const question = "based on the list papers '\"Why Are They Collecting My Data?\"- Inferring the Purposes of Network Traffic in Mobile Apps', 'A Study of User Privacy in Android Mobile AR Apps', 'Consistency Analysis of Data-Usage Purposes in Mobile Apps', 'Privacy and Security Analysis of mHealth Apps', 'Static Analysis for Android GDPR Complianc', 'An android intelligent mobile terminal application - field data survey system for forest fires', 'Needs, experiences, and views of people with rheumatic and musculoskeletal diseases on self-management mobile health apps - mixed methods study', 'Methods and Measures Used to Evaluate Patient-Operated Mobile Health Interventions - Scoping Literature Review', 'Hark - A Deep Learning System for Navigating Privacy Feedback at Scale', 'Features and characteristics of publicly available mHealth apps for self-management in chronic obstructive pulmonary disease', 'Detecting Malware by Analyzing App Permissions on Android Platform - A Systematic Literature Review', How can I present my research findings which, focus on 'Privacy compliance', in a clear and understandable way show me the sample?";
    //const question = "based on the list papers '\"Why Are They Collecting My Data?\"- Inferring the Purposes of Network Traffic in Mobile Apps', 'A Study of User Privacy in Android Mobile AR Apps', 'Consistency Analysis of Data-Usage Purposes in Mobile Apps', 'Privacy and Security Analysis of mHealth Apps', 'Static Analysis for Android GDPR Complianc', 'An android intelligent mobile terminal application - field data survey system for forest fires', 'Needs, experiences, and views of people with rheumatic and musculoskeletal diseases on self-management mobile health apps - mixed methods study', 'Methods and Measures Used to Evaluate Patient-Operated Mobile Health Interventions - Scoping Literature Review', 'Hark - A Deep Learning System for Navigating Privacy Feedback at Scale', 'Features and characteristics of publicly available mHealth apps for self-management in chronic obstructive pulmonary disease', 'Detecting Malware by Analyzing App Permissions on Android Platform - A Systematic Literature Review', what research methods are most suitable for the 'Privacy compliance' topics and list the related papers?";
    //const question = "Can I apply the NLP to determine the Consistency of the app between the app actual behavior and its privacy policy? Which paper apply the same approach?";
    
    //Hieu paper

    //const question = "based on the list papers 'Benefits and Barriers of Web 2.0 Technologies for Learning', 'Social_networking_teaching_and_learning', 'Benefits_barriers_and_prerequisites_for web2 learning activities', 'Teaching and learning sustainably with web 2 tech', 'Exploring the role of social media in coll learning', 'To use or not to use web 2.0 in higher education', 'Network form of organization', 'Usage, Barriers, and Training of Web 2.0', 'Social media and social networking applications for teaching learning', 'Web 2 education', what topic should I choose for my research focus on 'social networks in education' and the related papers?";
      //Based on the list of papers, a good topic for research focus on social networks in education could be "Benefits and Barriers of Using Social Networking Applications for Teaching and Learning." This topic is related to several of the papers listed and would allow for a comprehensive analysis of the use of social networks in education.
    const question = "based on the list papers below 'Benefits and Barriers of Web 2.0 Technologies for Learning', 'Social networking teaching and learning', 'Benefits barriers and prerequisites for web2 learning activities', 'Teaching and learning sustainably with web 2 tech', 'Exploring the role of social media in coll learning', 'To use or not to use web 2.0 in higher education', 'Network form of organization', 'Usage, Barriers, and Training of Web 2.0', 'Social media and social networking applications for teaching learning', 'Web 2 education', show some gaps in the current research which my study ‘social networks in education’ can fill?" 
      //
    //const question = "based on the list papers 'Benefits and Barriers of Web 2.0 Technologies for Learning', 'Social_networking_teaching_and_learning', 'Benefits_barriers_and_prerequisites_for web2 learning activities', 'Teaching and learning sustainably with web 2 tech', 'Exploring the role of social media in coll learning', 'To use or not to use web 2.0 in higher education', 'Network form of organization', 'Usage, Barriers, and Training of Web 2.0', 'Social media and social networking applications for teaching learning', 'Web 2 education', what should my research questions or hypotheses in the ‘social networks in education’ topics?";
      //
    //const question = "based on the list papers 'Benefits and Barriers of Web 2.0 Technologies for Learning', 'Social_networking_teaching_and_learning', 'Benefits_barriers_and_prerequisites_for web2 learning activities', 'Teaching and learning sustainably with web 2 tech', 'Exploring the role of social media in coll learning', 'To use or not to use web 2.0 in higher education', 'Network form of organization', 'Usage, Barriers, and Training of Web 2.0', 'Social media and social networking applications for teaching learning', 'Web 2 education', what research methods are most suitable for the ‘social networks in education’ topics?";
      //
    //const question = "based on the list papers 'Benefits and Barriers of Web 2.0 Technologies for Learning', 'Social_networking_teaching_and_learning', 'Benefits_barriers_and_prerequisites_for web2 learning activities', 'Teaching and learning sustainably with web 2 tech', 'Exploring the role of social media in coll learning', 'To use or not to use web 2.0 in higher education', 'Network form of organization', 'Usage, Barriers, and Training of Web 2.0', 'Social media and social networking applications for teaching learning', 'Web 2 education', how can I collect my data which, focus on 'social networks in education', in a way that is systematic, unbiased, and accurate?";
      //
    //const question = "based on the list papers 'Benefits and Barriers of Web 2.0 Technologies for Learning', 'Social_networking_teaching_and_learning', 'Benefits_barriers_and_prerequisites_for web2 learning activities', 'Teaching and learning sustainably with web 2 tech', 'Exploring the role of social media in coll learning', 'To use or not to use web 2.0 in higher education', 'Network form of organization', 'Usage, Barriers, and Training of Web 2.0', 'Social media and social networking applications for teaching learning', 'Web 2 education', what data analysis techniques are most suitable for the ‘social networks in education’ outcomes and explain?";
      //
    //const question = "based on the list papers 'Benefits and Barriers of Web 2.0 Technologies for Learning', 'Social_networking_teaching_and_learning', 'Benefits_barriers_and_prerequisites_for web2 learning activities', 'Teaching and learning sustainably with web 2 tech', 'Exploring the role of social media in coll learning', 'To use or not to use web 2.0 in higher education', 'Network form of organization', 'Usage, Barriers, and Training of Web 2.0', 'Social media and social networking applications for teaching learning', 'Web 2 education', how can I present my research findings which, focus on ‘social networks in education', in a clear and understandable way and explain?";
      //
    //const question = "based on the list papers 'Benefits and Barriers of Web 2.0 Technologies for Learning', 'Social_networking_teaching_and_learning', 'Benefits_barriers_and_prerequisites_for web2 learning activities', 'Teaching and learning sustainably with web 2 tech', 'Exploring the role of social media in coll learning', 'To use or not to use web 2.0 in higher education', 'Network form of organization', 'Usage, Barriers, and Training of Web 2.0', 'Social media and social networking applications for teaching learning', 'Web 2 education', Based on the list papers, can you list 5 Journal/Conference and the corresponding papers which is suitable for our 'social networks in education' article?";
      //

    await askQuestion(question);

    console.log("DONE");
  } catch (err) {
    console.log(err);
  }
}

async function askQuestion(question) {
  if (numTokens(question) > MAX_TOKEN_QUESTION)
    throw new Error("The question is too long");
  const similarityItems = await ChromaInstance.similaritySearch(question);

  const context = getContext(similarityItems);
  console.log(similarityItems);

  const chatPrompt = ChatPromptTemplate.fromPromptMessages([
    SystemMessagePromptTemplate.fromTemplate(
      `Based on this context: \n\n\n {context} \n\n\n Answer the question below as truthfully as you can, if you don’t know the answer, say you don’t know in a sarcastic way otherwise, just answer.`
    ),
    HumanMessagePromptTemplate.fromTemplate("{question}"),
  ]);
  const chain = new LLMChain({
    prompt: chatPrompt,
    llm: chat,
  });
  const res = await chain.call({
    context,
    question,
  });

  console.log(`A: ${res.text}`);
}
